#!/usr/bin/env python3
"""Generate images using Google's Gemini Nano Pro (gemini-3-pro-image-preview) model.

Usage:
    python generate_image.py --prompt "A sunset over mountains" [options]

Options:
    --prompt      TEXT    Image description (required)
    --filename    TEXT    Output filename without extension (default: auto-generated from prompt)
    --size        TEXT    Image size: 1K, 2K, or 4K (default: 1K)
    --aspect      TEXT    Aspect ratio: 1:1, 3:4, 4:3, 9:16, 16:9 (default: 1:1)
    --output-dir  TEXT    Output directory (default: public/generated-images)
"""

import argparse
import mimetypes
import os
import re
import sys

from google import genai
from google.genai import types


def sanitize_filename(prompt: str) -> str:
    """Convert a prompt into a safe filename."""
    name = prompt.lower().strip()[:60]
    name = re.sub(r"[^a-z0-9]+", "-", name)
    name = name.strip("-")
    return name or "generated-image"


def save_binary_file(file_path: str, data: bytes) -> None:
    with open(file_path, "wb") as f:
        f.write(data)
    print(f"Image saved to: {file_path}")


def generate_image(
    prompt: str,
    filename: str | None = None,
    size: str = "1K",
    aspect_ratio: str = "1:1",
    output_dir: str = "public/generated-images",
) -> str | None:
    """Generate an image and save it. Returns the saved file path or None on failure."""
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY environment variable is not set.", file=sys.stderr)
        sys.exit(1)

    # Validate inputs
    valid_sizes = ("1K", "2K", "4K")
    if size.upper() not in valid_sizes:
        print(f"Error: Invalid size '{size}'. Must be one of: {', '.join(valid_sizes)}", file=sys.stderr)
        sys.exit(1)
    size = size.upper()

    valid_ratios = ("1:1", "3:4", "4:3", "9:16", "16:9")
    if aspect_ratio not in valid_ratios:
        print(f"Error: Invalid aspect ratio '{aspect_ratio}'. Must be one of: {', '.join(valid_ratios)}", file=sys.stderr)
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    client = genai.Client(api_key=api_key)

    contents = [
        types.Content(
            role="user",
            parts=[types.Part.from_text(text=prompt)],
        ),
    ]

    generate_content_config = types.GenerateContentConfig(
        image_config=types.ImageConfig(
            aspect_ratio=aspect_ratio,
            image_size=size,
        ),
        response_modalities=["IMAGE", "TEXT"],
        tools=[types.Tool(googleSearch=types.GoogleSearch())],
    )

    base_name = filename or sanitize_filename(prompt)
    saved_path = None
    file_index = 0

    for chunk in client.models.generate_content_stream(
        model="gemini-3-pro-image-preview",
        contents=contents,
        config=generate_content_config,
    ):
        if chunk.parts is None:
            continue
        for part in chunk.parts:
            if part.inline_data and part.inline_data.data:
                ext = mimetypes.guess_extension(part.inline_data.mime_type) or ".png"
                suffix = f"_{file_index}" if file_index > 0 else ""
                file_name = f"{base_name}{suffix}{ext}"
                file_path = os.path.join(output_dir, file_name)
                save_binary_file(file_path, part.inline_data.data)
                if saved_path is None:
                    saved_path = file_path
                file_index += 1
            elif part.text:
                print(part.text)

    if saved_path is None:
        print("Warning: No image was generated by the model.", file=sys.stderr)

    return saved_path


def main():
    parser = argparse.ArgumentParser(description="Generate images using Gemini Nano Pro")
    parser.add_argument("--prompt", required=True, help="Image description")
    parser.add_argument("--filename", default=None, help="Output filename (without extension)")
    parser.add_argument("--size", default="1K", choices=["1K", "2K", "4K"], help="Image size (default: 1K)")
    parser.add_argument("--aspect", default="1:1", choices=["1:1", "3:4", "4:3", "9:16", "16:9"], help="Aspect ratio (default: 1:1)")
    parser.add_argument("--output-dir", default="public/generated-images", help="Output directory")
    args = parser.parse_args()

    generate_image(
        prompt=args.prompt,
        filename=args.filename,
        size=args.size,
        aspect_ratio=args.aspect,
        output_dir=args.output_dir,
    )


if __name__ == "__main__":
    main()
